pipelines with py3.11 on 3.1.1 branch (#2105)
* chore: formalize CPython 3.11 support (#2097)

(cherry picked from commit 381621701f2de4da91c526f1f8f2c6fc82c3216b)

# Conflicts:
#	docs/changes/4.0.0.rst
#	pyproject.toml
#	requirements/tests

* chore: use ranges for python 3.11 in the pipeline to allow versions after the rc1

(cherry picked from commit 8c03a682fa7b38ecbed9a35b3e2f2fd552467681)

* chore: work around Hypercorn bug in version 0.14.0 and 0.14.1

(cherry picked from commit bada83295dc181d09f1274bc7b5e5807fd845033)

* style: fix formatting

* chore: fix yaml syntax

* chore: remove authors that were added in v4 branch

* chore: re-add author that's in 3.1.1 release

* chore: use try/catch on corowrapper that was removed in python 3.11

* docs: ignore flake8 error on docstring that seem unsolvable

* chore: fix error on install
ModuleNotFoundError: No module named 'pbr'

* fix: typo in commit 26d3d741f9faf7ab3faaff7461f1c39d707be259

Co-authored-by: Vytautas Liuolia <vytautas.liuolia@gmail.com>