fix(test_cookies): case sensitivity
I got these errors while implementing the test suite in the AUR package for falcon.  It looks to be
missing proper capitalization.  Output has been tweaked to be less than 100 characters per line.

======================================================================
FAIL: test_response_base_case (tests.test_cookies.TestCookies)
tests.test_cookies.TestCookies.test_response_base_case
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/carl/aur/python-falcon/falcon-0.3.0/tests/test_cookies.py", line 60, in
  test_response_base_case
    self.srmock.headers)
  File "/usr/lib/python3.4/site-packages/testtools/testcase.py", line 356, in assertIn
    self.assertThat(haystack, Contains(needle), message)
  File "/usr/lib/python3.4/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError:
('set-cookie', 'foo=bar; Domain=example.com; httponly; Path=/; secure')
not in
[
('content-length', '0'),
('set-cookie', 'foo=bar; Domain=example.com; HttpOnly; Path=/; Secure')
]

======================================================================
FAIL: test_response_complex_case (tests.test_cookies.TestCookies)
tests.test_cookies.TestCookies.test_response_complex_case
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/home/carl/aur/python-falcon/falcon-0.3.0/tests/test_cookies.py", line 67, in
  test_response_complex_case
    self.srmock.headers)
  File "/usr/lib/python3.4/site-packages/testtools/testcase.py", line 356, in assertIn
    self.assertThat(haystack, Contains(needle), message)
  File "/usr/lib/python3.4/site-packages/testtools/testcase.py", line 435, in assertThat
    raise mismatch_error
testtools.matchers._impl.MismatchError:
('set-cookie', 'foo=bar; httponly; Max-Age=300; secure')
not in
[
('content-type', 'application/json; charset=utf-8'),
('set-cookie', 'bar=baz; Secure'),
('set-cookie', 'foo=bar; HttpOnly; Max-Age=300; Secure')
]