django.conf.urls.url() was deprecated in Django 3.0, and is removed in Django 4.0+.
Running docker bench_py3.Dockerfile ends with error:

 File "/usr/local/lib/python3.8/site-packages/falcon/bench/dj/dj/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.8/site-packages/django/conf/urls/__init__.py)